version: 0.1

environment_variables:
  plaintext:
    S3_BUCKET: "currency-converter-bucket"

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp build s3://${S3_BUCKET} --recursive

artifacts:
  files:
    - build*/**
  discard-paths: yes
